### ISSUE TITLE
Fix: Typo and wording of description in readme

### ISSUE THREAD

**Issue by ValerioCipolla** [ValerioCipolla/blobfish-ui#11]
**Describe the bug**
The description of the project in the readme has a typo in the spelling of the word "components" and is worded wrong.

**To Reproduce**
Go to readme and read first line after title.

**Expected behavior**
It should say instead: "Open Source Project for beginners. A playground UI library published on npm to practice creating components with React and TypeScript."

**Comment by clarazhangg** [comment]
@ValerioCipolla Hi there! Can I help fix the typo?
